### ISSUE TITLE
Export patroni image data from cas-postgres values.yaml for reuse in parent charts

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-postgres#115]
It is possible for a parent chart to use values from a subchart if the subchart's values.yaml has an `exports` field at the root.
https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies

It would be helpful to reuse the patroni image from the cas-postgres repo in the charts that consume it as a subchart. Besides ease of use, this helps to ensure that the image we're using in cas-postgres is what is being used in the parent consuming the subchart. If we hardcode image data in the parent, and change image data in cas-postgres, it's possible to miss changes that may contain important security updates.

To do this add this to the cas-postgres values.yaml.

```
exports:
  patroni_image:
    repository: <repository>
    pullPolicy: <policy>
    tag: <tag>
```
